import { trans } from "i18n";

const names: Record<string, string> = {
  "label.text": trans("componentDoc.labelText"),
  "label.position": trans("componentDoc.labelPosition"),
  "label.align": trans("componentDoc.labelAlign"),
  "options.optionType": trans("componentDoc.optionsOptionType"),
  "style.backgroundColor": trans("componentDoc.styleBackgroundColor"),
  "style.borderColor": trans("componentDoc.styleBorderColor"),
  "style.color": trans("componentDoc.styleColor"),
  "selection.mode": trans("componentDoc.selectionMode"),
  "pagination.showSizeChanger": trans("componentDoc.paginationShowSizeChangerButton"),
  "pagination.showQuickJumper": trans("componentDoc.paginationShowQuickJumper"),
  "pagination.hideOnSinglePage": trans("componentDoc.paginationHideOnSinglePage"),
  "pagination.pageSizeOptions": trans("componentDoc.paginationPageSizeOptions"),
  "chartConfig.compType": trans("componentDoc.chartConfigCompType"),
  "xConfig.type": trans("componentDoc.xAxisType"),
  placeholder: trans("componentDoc.placeholder"),
  default: trans("componentDoc.value"),
  loading: trans("componentDoc.loading"),
  disabled: trans("componentDoc.disabled"),
  required: trans("componentDoc.required"),
  minLength: trans("componentDoc.minLength"),
  maxLength: trans("componentDoc.maxLength"),
  showCount: trans("componentDoc.showCount"),
  autoHeight: trans("componentDoc.autoHeight"),
  thousandsSeparator: trans("componentDoc.thousandsSeparator"),
  precision: trans("componentDoc.precision"),
  value: trans("componentDoc.value"),
  formatter: trans("componentDoc.format"),
  min: trans("componentDoc.min"),
  max: trans("componentDoc.max"),
  step: trans("componentDoc.step"),
  start: trans("componentDoc.start"),
  end: trans("componentDoc.end"),
  allowHalf: trans("componentDoc.allowHalf"),
  filetype: trans("componentDoc.filetype"),
  showUploadList: trans("componentDoc.showUploadList"),
  uploadType: trans("componentDoc.uploadType"),
  allowClear: trans("componentDoc.allowClear"),
  minSize: trans("componentDoc.minSize"),
  maxSize: trans("componentDoc.maxSize"),
  maxFiles: trans("componentDoc.maxFiles"),
  format: trans("componentDoc.format"),
  minDate: trans("componentDoc.minDate"),
  maxDate: trans("componentDoc.maxDate"),
  minTime: trans("componentDoc.minTime"),
  maxTime: trans("componentDoc.maxTime"),
  text: trans("componentDoc.text"),
  type: trans("componentDoc.type"),
  hideHeader: trans("componentDoc.hideHeader"),
  hideBordered: trans("componentDoc.hideBordered"),
  src: trans("componentDoc.src"),
  showInfo: trans("componentDoc.showInfo"),
  mode: trans("componentDoc.mode"),
  onlyMenu: trans("componentDoc.onlyMenu"),
  horizontalAlignment: trans("componentDoc.horizontalAlignment"),
};

export default names;
