apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openblocks-stacks
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
