export const data = [
  {
    key: "1",
    firstName: "John",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1",
  },
  {
    key: "2",
    firstName: "Jim",
    lastName: "Green",
    age: 42,
    address: "London No. 1 ",
  },
  {
    key: "3",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 ",
  },
  {
    key: "4",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 ",
  },
  {
    key: "5",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 ",
  },
  {
    key: "6",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 ",
  },
  {
    key: "7",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 ",
  },
  {
    key: "8",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 ",
  },
  {
    key: "9",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 ",
  },
  {
    key: "10",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 ",
  },
  {
    key: "11",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 ",
  },
  {
    key: "12",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 ",
  },
];
