export const ReduxActionTypes = {
  /* user auth RELATED */
  LOGOUT_USER_INIT: "LOGOUT_USER_INIT", // logout
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS", // logout succeed, reset state
  FETCH_USER_INIT: "FETCH_USER_INIT", // fetch some info of the current user
  FETCH_USER_DETAILS_SUCCESS: "FETCH_USER_DETAILS_SUCCESS", // fetch info succeed
  FETCH_CURRENT_USER_SUCCESS: "FETCH_CURRENT_USER_SUCCESS",
  FETCH_RAW_CURRENT_USER: "FETCH_RAW_CURRENT_USER",
  FETCH_RAW_CURRENT_USER_SUCCESS: "FETCH_RAW_CURRENT_USER_SUCCESS",

  /* plugin RELATED */
  FETCH_DATA_SOURCE_TYPES: "FETCH_DATA_SOURCE_TYPES",
  FETCH_DATA_SOURCE_TYPES_SUCCESS: "FETCH_DATA_SOURCE_TYPES_SUCCESS",
  /* << plugin RELATED */

  /* datasource RELATED */
  FETCH_DATASOURCE_INIT: "FETCH_DATASOURCE_INIT",
  FETCH_DATASOURCE_BY_APP_INIT: "FETCH_DATASOURCE_BY_APP_INIT",
  FETCH_DATASOURCE_SUCCESS: "FETCH_DATASOURCE_SUCCESS",
  FETCH_DATASOURCE_STRUCTURE_INIT: "FETCH_DATASOURCE_STRUCTURE_INIT",
  FETCH_DATASOURCE_STRUCTURE_SUCCESS: "FETCH_DATASOURCE_STRUCTURE_SUCCESS",
  CREATE_DATASOURCE_INIT: "CREATE_DATASOURCE_INIT",
  CREATE_DATASOURCE_SUCCESS: "CREATE_DATASOURCE_SUCCESS",
  UPDATE_DATASOURCE_INIT: "UPDATE_DATASOURCE_INIT",
  UPDATE_DATASOURCE_SUCCESS: "UPDATE_DATASOURCE_SUCCESS",
  DELETE_DATASOURCE_INIT: "DELETE_DATASOURCE_INIT",
  DELETE_DATASOURCE_SUCCESS: "DELETE_DATASOURCE_SUCCESS",

  FETCH_DATASOURCE_PERMISSION_INIT: "FETCH_DATASOURCE_PERMISSION_INIT",
  FETCH_DATASOURCE_PERMISSION_SUCCESS: "FETCH_DATASOURCE_PERMISSION_SUCCESS",
  GRANT_DATASOURCE_PERMISSION_INIT: "GRANT_DATASOURCE_PERMISSION_INIT",
  UPDATE_DATASOURCE_PERMISSION_INIT: "UPDATE_DATASOURCE_PERMISSION_INIT",
  UPDATE_DATASOURCE_PERMISSION_SUCCESS: "UPDATE_DATASOURCE_PERMISSION_SUCCESS",
  DELETE_DATASOURCE_PERMISSION_INIT: "DELETE_DATASOURCE_PERMISSION_INIT",
  DELETE_DATASOURCE_PERMISSION_SUCCESS: "DELETE_DATASOURCE_PERMISSION_SUCCESS",
  /* << datasource RELATED */

  /* query RELATED */
  FETCH_QUERY_LIBRARY_BY_ORG_INIT: "FETCH_QUERY_LIBRARY_BY_ORG_INIT",
  FETCH_QUERY_LIBRARY_BY_ORG_SUCCESS: "FETCH_QUERY_LIBRARY_BY_ORG_SUCCESS",
  FETCH_QUERY_LIBRARY_DROPDOWN_INIT: "FETCH_QUERY_LIBRARY_DROPDOWN_INIT",
  FETCH_QUERY_LIBRARY_DROPDOWN_SUCCESS: "FETCH_QUERY_LIBRARY_DROPDOWN_SUCCESS",
  CREATE_QUERY_LIBRARY_INIT: "CREATE_QUERY_LIBRARY_INIT",
  CREATE_QUERY_LIBRARY_SUCCESS: "CREATE_QUERY_LIBRARY_SUCCESS",
  UPDATE_QUERY_LIBRARY_INIT: "UPDATE_QUERY_LIBRARY_INIT",
  UPDATE_QUERY_LIBRARY_SUCCESS: "UPDATE_QUERY_LIBRARY_SUCCESS",
  DELETE_QUERY_LIBRARY_INIT: "DELETE_QUERY_LIBRARY_INIT",
  DELETE_QUERY_LIBRARY_SUCCESS: "DELETE_QUERY_LIBRARY_SUCCESS",

  FETCH_QUERY_LIBRARY_RECORD_DSL_INIT: "FETCH_QUERY_LIBRARY_RECORD_DSL_INIT",
  FETCH_QUERY_LIBRARY_RECORD_DSL_SUCCESS: "FETCH_QUERY_LIBRARY_RECORD_DSL_SUCCESS",
  FETCH_QUERY_LIBRARY_RECORD: "FETCH_QUERY_LIBRARY_RECORD",
  FETCH_QUERY_LIBRARY_RECORD_SUCCESS: "FETCH_QUERY_LIBRARY_RECORD_SUCCESS",
  CREATE_QUERY_LIBRARY_RECORD: "CREATE_QUERY_LIBRARY_RECORD",
  CREATE_QUERY_LIBRARY_RECORD_SUCCESS: "CREATE_QUERY_LIBRARY_RECORD_SUCCESS",
  /* << query RELATED */

  /* folder RELATED */
  CREATE_FOLDER_INIT: "CREATE_FOLDER_INIT",
  CREATE_FOLDER_SUCCESS: "CREATE_FOLDER_SUCCESS",
  UPDATE_FOLDER_INIT: "UPDATE_FOLDER_INIT",
  UPDATE_FOLDER_SUCCESS: "UPDATE_FOLDER_SUCCESS",
  DELETE_FOLDER_INIT: "DELETE_FOLDER_INIT",
  DELETE_FOLDER_SUCCESS: "DELETE_FOLDER_SUCCESS",
  MOVE_TO_FOLDER_INIT: "MOVE_TO_FOLDER_INIT",
  MOVE_TO_FOLDER_SUCCESS: "MOVE_TO_FOLDER_SUCCESS",
  FETCH_FOLDER_ELEMENTS_INIT: "FETCH_FOLDER_ELEMENTS_INIT",
  FETCH_FOLDER_ELEMENTS_SUCCESS: "FETCH_FOLDER_ELEMENTS_SUCCESS",
  FETCH_ALL_FOLDERS_INIT: "FETCH_ALL_FOLDERS_INIT",
  FETCH_ALL_FOLDERS_SUCCESS: "FETCH_ALL_FOLDERS_SUCCESS",
  /* << folder RELATED */

  /* organization group user RELATED */
  UPDATE_GROUP_INFO: "UPDATE_GROUP_INFO",
  FETCH_ORG_GROUPS: "FETCH_ORG_GROUPS", // fetch group list
  FETCH_ORG_GROUPS_SUCCESS: "FETCH_ORG_GROUPS_SUCCESS",
  UPDATE_USER_ORG_ROLE: "UPDATE_USER_ORG_ROLE",
  UPDATE_USER_GROUP_ROLE: "UPDATE_USER_GROUP_ROLE",
  FETCH_ORG_ALL_USERS: "FETCH_ORG_ALL_USERS",
  FETCH_ORG_ALL_USERS_SUCCESS: "FETCH_ORG_ALL_USERS_SUCCESS",
  FETCH_GROUP_USERS: "FETCH_GROUP_USERS",
  FETCH_GROUP_USERS_SUCCESS: "FETCH_GROUP_USERS_SUCCESS",
  DELETE_GROUP_USER: "DELETE_GROUP_USER", // delete user from group
  DELETE_GROUP_USER_SUCCESS: "DELETE_GROUP_USER_SUCCESS",
  ADD_GROUP_USER: "ADD_GROUP_USER",
  ADD_GROUP_USER_SUCCESS: "ADD_GROUP_USER_SUCCESS",
  DELETE_ORG_USER: "DELETE_ORG_USER",
  DELETE_ORG_USER_SUCCESS: "DELETE_ORG_USER_SUCCESS",
  QUIT_GROUP: "QUIT_GROUP",
  QUIT_GROUP_SUCCESS: "QUIT_GROUP_SUCCESS",
  QUIT_ORG: "QUIT_ORG",
  SWITCH_ORG: "SWITCH_ORG",
  CREATE_ORG: "CREATE_ORG",
  CREATE_ORG_SUCCESS: "CREATE_ORG_SUCCESS",
  DELETE_ORG: "DELETE_ORG",
  DELETE_ORG_SUCCESS: "DELETE_ORG_SUCCESS",
  UPDATE_ORG: "UPDATE_ORG",
  UPDATE_ORG_SUCCESS: "UPDATE_ORG_SUCCESS",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  UPDATE_USER_PROFILE_SUCCESS: "UPDATE_USER_PROFILE_SUCCESS",
  UPLOAD_USER_HEAD_SUCCESS: "UPLOAD_USER_HEAD_SUCCESS", // update avatar
  MARK_USER_STATUS: "MARK_USER_STATUS",

  /* home data */
  FETCH_HOME_DATA: "FETCH_HOME_DATA",
  FETCH_HOME_DATA_SUCCESS: "FETCH_HOME_DATA_SUCCESS",

  /* application RELATED */
  CREATE_APPLICATION_INIT: "CREATE_APPLICATION_INIT",
  CREATE_APPLICATION_SUCCESS: "CREATE_APPLICATION_SUCCESS",
  DELETE_APPLICATION_INIT: "DELETE_APPLICATION_INIT",
  DELETE_APPLICATION_SUCCESS: "DELETE_APPLICATION_SUCCESS",
  UPDATE_APPLICATION: "UPDATE_APPLICATION",
  UPDATE_APPLICATION_META: "UPDATE_APPLICATION_META",
  PUBLISH_APPLICATION: "PUBLISH_APPLICATION",
  PUBLISH_APPLICATION_SUCCESS: "PUBLISH_APPLICATION_SUCCESS",
  UPDATE_APPLICATION_META_SUCCESS: "UPDATE_APPLICATION_META_SUCCESS",
  FETCH_APPLICATION_DETAIL: "FETCH_APPLICATION_DETAIL",
  FETCH_APP_PUBLISH_DETAIL_SUCCESS: "FETCH_APP_PUBLISH_DETAIL_SUCCESS", // fetching the publish edition succeed
  FETCH_APP_EDITING_DETAIL_SUCCESS: "FETCH_APP_EDITING_DETAIL_SUCCESS", // fetching the editting edition succeed
  FETCH_APP_PERMISSIONS: "FETCH_APPLICATION_PERMISSIONS",
  FETCH_APP_PERMISSIONS_SUCCESS: "FETCH_APP_PERMISSIONS_SUCCESS",
  UPDATE_APP_PERMISSION: "UPDATE_APP_PERMISSION",
  UPDATE_APP_PERMISSION_SUCCESS: "UPDATE_APP_PERMISSION_SUCCESS",
  DELETE_APP_PERMISSION: "DELETE_APP_PERMISSION",
  DELETE_APP_PERMISSION_SUCCESS: "DELETE_APP_PERMISSION_SUCCESS",
  UPDATE_APP_PERMISSION_INFO: "UPDATE_APP_PERMISSION_INFO",
  RECYCLE_APPLICATION_INIT: "RECYCLE_APPLICATION_INIT",
  RECYCLE_APPLICATION_SUCCESS: "RECYCLE_APPLICATION_SUCCESS",
  RESTORE_APPLICATION_INIT: "RESTORE_APPLICATION_INIT",
  RESTORE_APPLICATION_SUCCESS: "RESTORE_APPLICATION_SUCCESS",
  FETCH_APPLICATION_RECYCLE_LIST_INIT: "FETCH_APPLICATION_RECYCLE_LIST_INIT",
  FETCH_APPLICATION_RECYCLE_LIST_SUCCESS: "FETCH_APPLICATION_RECYCLE_LIST_SUCCESS",
  FETCH_ALL_APPLICATIONS_INIT: "FETCH_ALL_APPLICATIONS_INIT",
  FETCH_ALL_APPLICATIONS_SUCCESS: "FETCH_ALL_APPLICATIONS_SUCCESS",
  FETCH_ALL_MODULES_INIT: "FETCH_ALL_MODULES_INIT",
  FETCH_ALL_MODULES_SUCCESS: "FETCH_ALL_MODULES_SUCCESS",

  /* user profile */
  SET_USER_PROFILE_SETTING_MODAL_VISIBLE: "SET_USER_PROFILE_SETTING_MODAL_VISIBLE",

  /* system config */
  FETCH_SYS_CONFIG_INIT: "FETCH_SYS_CONFIG_INIT",
  FETCH_SYS_CONFIG_SUCCESS: "FETCH_SYS_CONFIG_SUCCESS",
  SET_EDITOR_EXTERNAL_STATE: "SET_EDITOR_EXTERNAL_STATE",

  /* audit log */
  FETCH_AUDIT_EVENT: "FETCH_AUDIT_EVENT",
  FETCH_AUDIT_EVENT_SUCCESS: "FETCH_AUDIT_EVENT_SUCCESS",
  FETCH_AUDIT_LOG: "FETCH_AUDIT_LOG",
  FETCH_AUDIT_LOG_SUCCESS: "FETCH_AUDIT_LOG_SUCCESS",

  /* application snapshot */
  FETCH_APP_SNAPSHOTS: "FETCH_APP_SNAPSHOTS",
  FETCH_APP_SNAPSHOTS_SUCCESS: "FETCH_APP_SNAPSHOTS_SUCCESS",
  FETCH_APP_SNAPSHOT_DSL: "FETCH_APP_SNAPSHOT_DSL",
  FETCH_APP_SNAPSHOT_DSL_SUCCESS: "FETCH_APP_SNAPSHOT_DSL_SUCCESS",
  RECOVER_APP_SNAPSHOT: "RECOVER_APP_SNAPSHOT",
  CREATE_APP_SNAPSHOT: "CREATE_APP_SNAPSHOT",
  CREATE_APP_SNAPSHOT_SUCCESS: "CREATE_APP_SNAPSHOT_SUCCESS",
  SET_SHOW_APP_SNAPSHOT: "SET_SHOW_APP_SNAPSHOT",
  SET_SELECT_SNAPSHOT_ID: "SET_SELECT_SNAPSHOT_ID",

  /* common setting */
  FETCH_COMMON_SETTING: "FETCH_COMMON_SETTING",
  FETCH_COMMON_SETTING_SUCCESS: "FETCH_COMMON_SETTING_SUCCESS",
  SET_COMMON_SETTING: "SET_COMMON_SETTING",
  SET_COMMON_SETTING_SUCCESS: "SET_COMMON_SETTING_SUCCESS",

  /* npm plugin */
  PACKAGE_META_READY: "PACKAGE_META_READY",
  SELECT_PACKAGE_VERSION: "SELECT_PACKAGE_VERSION",

  /* js library */
  FETCH_JS_LIB_METAS: "FETCH_JS_LIB_METAS",
  FETCH_JS_LIB_METAS_SUCCESS: "FETCH_JS_LIB_METAS_SUCCESS",
  FETCH_JS_LIB_RECOMMENDS: "FETCH_JS_LIB_RECOMMENDS",
  FETCH_JS_LIB_RECOMMENDS_SUCCESS: "FETCH_JS_LIB_RECOMMENDS_SUCCESS",
};

export const ReduxActionErrorTypes = {
  API_ERROR: "API_ERROR",
  /* user RELATED */
  FETCH_USER_DETAILS_ERROR: "FETCH_USER_DETAILS_ERROR",
  FETCH_CURRENT_USER_ERROR: "FETCH_CURRENT_USER_ERROR",
  UPDATE_USER_PROFILE_ERROR: "UPDATE_USER_PROFILE_ERROR",
  /* organization group user RELATED */
  CREATE_ORG_ERROR: "CREATE_ORG_ERROR",
  FETCH_ORG_GROUPS_ERROR: "FETCH_ORG_GROUPS_ERROR",
  /* query RELATED */
  FETCH_QUERIES_ERROR: "FETCH_QUERIES_ERROR", // fetching query list failed
  /* << query RELATED */

  /* application RELATED */
  CREATE_APPLICATION_ERROR: "CREATE_APPLICATION_ERROR",
  DELETE_APPLICATION_ERROR: "DELETE_APPLICATION_ERROR",
  FETCH_APPLICATION_DETAIL_ERROR: "FETCH_APPLICATION_DETAIL_ERROR",
  PUBLISH_APPLICATION_ERROR: "PUBLISH_APPLICATION_ERROR",
  FETCH_HOME_DATA_ERROR: "FETCH_HOME_DATA_ERROR",
  FETCH_FOLDER_ELEMENTS_ERROR: "FETCH_FOLDER_ELEMENTS_ERROR",

  /* sytem config */
  FETCH_SYS_CONFIG_ERROR: "FETCH_SYS_CONFIG_ERROR",

  /* application snapshot */
  CREATE_APP_SNAPSHOT_ERROR: "CREATE_APP_SNAPSHOT_ERROR",
  FETCH_APP_SNAPSHOTS_ERROR: "FETCH_APP_SNAPSHOTS_ERROR",
  FETCH_APP_SNAPSHOT_DSL_ERROR: "FETCH_APP_SNAPSHOT_DSL_ERROR",
};

export type ReduxActionType = typeof ReduxActionTypes[keyof typeof ReduxActionTypes];
export type ReduxActionErrorType = typeof ReduxActionErrorTypes[keyof typeof ReduxActionErrorTypes];

export interface ReduxAction<T> {
  type: ReduxActionType | ReduxActionErrorType;
  payload: T;
}

export type ReduxActionWithoutPayload = Pick<ReduxAction<undefined>, "type">;

export interface EvaluationReduxAction<T> extends ReduxAction<T> {
  postEvalActions?: Array<ReduxAction<any> | ReduxActionWithoutPayload>;
}

export interface ReduxActionWithCallbacks<T, S, E> extends ReduxAction<T> {
  onSuccess?: ReduxAction<S>;
  onError?: ReduxAction<E>;
  onSuccessCallback?: (response: S) => void;
  onErrorCallback?: (error: E) => void;
}

export interface PromisePayload {
  reject: any;
  resolve: any;
}

export interface ReduxActionWithPromise<T> extends ReduxAction<T> {
  payload: T & PromisePayload;
}
