export const Data = {
  ui: {
    layout: {
      "95357c7c": {
        i: "95357c7c",
        h: 5,
        w: 3,
        x: 0,
        y: -9929,
        isDraggable: true,
        resizeHandles: [],
      },
      "54b2f7a0": {
        i: "54b2f7a0",
        h: 35,
        w: 15,
        x: 0,
        y: 0,
        isDraggable: true,
        resizeHandles: [],
      },
      a65d9d4b: {
        i: "a65d9d4b",
        h: 5,
        w: 5,
        x: 17,
        y: 14,
        isDraggable: true,
        resizeHandles: [],
      },
      f7a344a: {
        i: "f7a344a",
        h: 5,
        w: 7,
        x: 0,
        y: 37,
        isDraggable: true,
        resizeHandles: ["e", "w"],
      },
      "7522223a": {
        i: "7522223a",
        h: 5,
        w: 6,
        x: 12,
        y: 41,
        isDraggable: true,
        resizeHandles: [],
      },
      "43c9a017": {
        i: "43c9a017",
        h: 19,
        w: 4,
        x: 0,
        y: 47,
        isDraggable: true,
        resizeHandles: [],
      },
      be67942f: {
        i: "be67942f",
        h: 45,
        w: 8,
        x: 16,
        y: 111,
        isDraggable: true,
        resizeHandles: [],
      },
    },
    items: {
      "95357c7c": {
        compType: "button",
        comp: {
          buttonType: "primary",
          text: "Button",
          onEvent: [],
          disabled: "",
          loading: "",
          style: {
            backgroundColor: { color: "" },
            borderColor: { color: "" },
            color: { color: "" },
          },
          hidden: "",
        },
        name: "button1",
      },
      be67942f: {
        compType: "jsonSchemaForm",
        comp: {
          schema:
            '{\n "title": "User Information",\n "description": "Form example",\n "type": "object",\n "required": [\n  "name",\n  "phone"\n ],\n "properties": {\n  "name": {\n   "type": "string",\n   "title": "Name"\n  },\n  "phone": {\n   "type": "string",\n   "title": "Phone",\n   "minLength": 11\n  },\n  "birthday": {\n   "type": "string",\n   "title": "Birthday"\n  }\n }\n}',
          uiSchema:
            '{\n "name": {\n  "ui:autofocus": true,\n  "ui:emptyValue": ""\n },\n "phone": {\n  "ui:help": "11 digits"\n },\n "birthday": {\n  "ui:widget": "date"\n }\n}',
          data: '{\n "name": "David",\n "phone": "13488886666",\n "birthday": "1980-03-16"\n}',
          onEvent: [],
          hidden: "",
        },
        name: "jsonSchemaForm1",
      },
      "43c9a017": {
        compType: "progressCircle",
        comp: { value: "{{slider1.value - switch1.value*10}}", hidden: "" },
        name: "progressCircle1",
      },
      "7522223a": {
        compType: "time",
        comp: {
          value: "",
          label: { text: "Label", tooltip: "", align: "right" },
          format: "",
          disabled: "",
          onEvent: [],
          showTime: false,
          use12Hours: false,
          hourStep: "",
          minuteStep: "",
          secondStep: "",
          required: false,
          minDate: "",
          maxDate: "",
          minTime: "",
          maxTime: "",
          hidden: "",
        },
        name: "time1",
      },
      a65d9d4b: {
        compType: "switch",
        comp: {
          value: "",
          label: { text: "Label", tooltip: "", align: "right" },
          onEvent: [],
          disabled: "",
          hidden: "",
        },
        name: "switch1",
      },
      "54b2f7a0": {
        compType: "chart",
        comp: {
          title: "",
          data: '[\n {\n  "date": "2021-09",\n  "department": "Admin",\n  "spending": 9003,\n  "budget": 8000\n },\n {\n  "date": "2021-09",\n  "department": "Finance",\n  "spending": 3033,\n  "budget": 4000\n },\n {\n  "date": "2021-09",\n  "department": "Sales",\n  "spending": 9230,\n  "budget": 8000\n },\n {\n  "date": "2021-10",\n  "department": "Admin",\n  "spending": 13032,\n  "budget": 15000\n },\n {\n  "date": "2021-10",\n  "department": "Finance",\n  "spending": 2300,\n  "budget": 5000\n },\n {\n  "date": "2021-10",\n  "department": "Sales",\n  "spending": 7323.5,\n  "budget": 8000\n },\n {\n  "date": "2021-11",\n  "department": "Admin",\n  "spending": 13000,\n  "budget": 16023\n },\n {\n  "date": "2021-11",\n  "department": "Finance",\n  "spending": 3569.5,\n  "budget": 3000\n },\n {\n  "date": "2021-11",\n  "department": "Sales",\n  "spending": 10000,\n  "budget": 9932\n },\n {\n  "date": "2021-12",\n  "department": "Admin",\n  "spending": 18033,\n  "budget": 20000\n },\n {\n  "date": "2021-12",\n  "department": "Finance",\n  "spending": 4890,\n  "budget": 4500\n },\n {\n  "date": "2021-12",\n  "department": "Sales",\n  "spending": 9322,\n  "budget": 8000\n }\n]',
          xAxisKey: "date",
          xAxisDirection: "horizontal",
          series: [
            {
              columnName: "department",
              seriesName: "Cost",
              hide: false,
              dataIndex: "e686d3cb",
            },
          ],
          xConfig: { axisName: "", type: "default" },
          yConfig: { axisName: "", type: "category" },
          legendConfig: { position: "bottom" },
          onEvent: [],
          chartConfig: { compType: "bar", comp: { type: "basicBar" } },
          hidden: "",
        },
        name: "chart1",
      },
      f7a344a: {
        compType: "slider",
        comp: {
          value: "",
          max: "100",
          min: "0",
          step: "1",
          label: { text: "Label", tooltip: "", align: "right" },
          disabled: "",
          onEvent: [],
          hidden: "",
        },
        name: "slider1",
      },
    },
  },
  queries: [
    {
      compType: "restApi",
      comp: {
        httpMethod: "GET",
        path: "",
        cookies: [{ key: "", value: "" }],
        headers: [{ key: "", value: "" }],
        parameters: [{ key: "", value: "" }],
        bodyType: "none",
        body: "",
        bodyFormData: [{ key: "", value: "", type: "text" }],
        timeout: "10000",
      },
      id: "i5itgc2ir26o2hf13m7vqn50",
      name: "xxxy22",
      datasourceId: "626b88c853dcda1cf9fafb4f",
      triggerType: "manual",
      onEvent: [],
    },
  ],
};
