export const ROOT_COMP_VALUE = {
  ui: {
    layout: [
      {
        w: 4,
        h: 5,
        x: 15,
        y: 0,
        i: "f1a550ef",
        moved: false,
        static: false,
        isDraggable: true,
        resizeHandles: [],
      },
      {
        w: 6,
        h: 5,
        x: 8,
        y: 2,
        i: "91816a3",
        moved: false,
        static: false,
        isDraggable: true,
        resizeHandles: [],
      },
      {
        w: 6,
        h: 5,
        x: 0,
        y: 2,
        i: "18f4f3f6",
        moved: false,
        static: false,
        isDraggable: true,
        resizeHandles: [],
      },
      {
        w: 18,
        h: 140,
        x: 0,
        y: 11,
        i: "5ea4f2dc",
        moved: false,
        static: false,
        isDraggable: true,
        resizeHandles: [],
      },
    ],
    items: {
      f1a550ef: {
        compType: "button",
        comp: {
          buttonType: "default",
          text: "button",
          onClick: { compType: "empty", comp: {} },
          hidden: "{{switch1.checked}}",
        },
        name: "button1",
      },
      "91816a3": {
        compType: "switch",
        comp: {
          checked: { value: false, defaultValue: "" },
          label: { text: "Label", tooltip: "", align: "right" },
          disabled: false,
        },
        name: "switch1",
      },
      "18f4f3f6": {
        compType: "select",
        comp: {
          value: { value: "", defaultValue: "number1" },
          labels: '["option1","option2","option3"]',
          values: '["number1","number2","number3"]',
          label: { text: "label", tooltip: "", align: "right" },
          placeholder: "",
        },
        name: "select1",
      },
      "5ea4f2dc": {
        compType: "table",
        comp: {
          hideBordered: false,
          hideHeader: false,
          data: '[\n {\n  "ID": 1,\n  "name": "a",\n  "date": "2021-05-17",\n  "mail": "romario70@qq.com",\n  "phone": "17137564247",\n  "sex": "male"\n },\n {\n  "ID": 2,\n  "name": "b",\n  "date": "2019-07-16",\n  "mail": "lovely.luzixuan@163.com",\n  "phone": "17110230998",\n  "sex": "female"\n },\n {\n  "ID": 3,\n  "name": "b",\n  "date": "2020-12-27",\n  "mail": "gisel_bin34@qq.com",\n  "phone": "18875259170",\n  "sex": "male"\n },\n {\n  "ID": 4,\n  "name": "c",\n  "date": "2019-11-28",\n  "mail": "wilma68@163.com",\n  "phone": "17111461612",\n  "sex": "male"\n },\n {\n  "ID": 5,\n  "name": "d",\n  "date": "2019-12-03",\n  "mail": "silencer_gong@gmail.com",\n  "phone": "16683012636",\n  "sex": "male"\n },\n {\n  "ID": 6,\n  "name": "e",\n  "date": "2019-06-03",\n  "mail": "liu_reynolds34@126.com",\n  "phone": "18888119131",\n  "sex": "female"\n },\n {\n  "ID": 7,\n  "name": "f",\n  "date": "2020-02-09",\n  "mail": "realmadrID_xiao1995@gmail.com",\n  "phone": "18871452348",\n  "sex": "female"\n },\n {\n  "name": "g",\n  "date": "2019-07-14",\n  "mail": "rachelle5@gmail.com",\n  "phone": "13254036165",\n  "sex": "male",\n  "ID": 8\n },\n {\n  "name": "h",\n  "date": "2019-07-11",\n  "mail": "mingzhe67@sina.com",\n  "phone": "17155089400",\n  "sex": "female",\n  "ID": 9\n },\n {\n  "name": "i",\n  "date": "2021-05-29",\n  "mail": "zelma.dai@hotmail.com",\n  "phone": "18849094541",\n  "sex": "female",\n  "ID": 10\n },\n {\n  "name": "j",\n  "date": "2020-05-02",\n  "mail": "joannie_beatty88@gmail.com",\n  "phone": "13234021406",\n  "sex": "female",\n  "ID": 11\n },\n {\n  "name": "k",\n  "date": "2022-03-08",\n  "mail": "carlos_crona66@sina.com",\n  "phone": "13256894564",\n  "sex": "female",\n  "ID": 12\n },\n {\n  "name": "l",\n  "date": "2019-11-28",\n  "mail": "garland_labadie@sohu.com",\n  "phone": "13104286197",\n  "sex": "male",\n  "ID": 13\n },\n {\n  "name": "m",\n  "date": "2021-01-02",\n  "mail": "mitchel75@sohu.com",\n  "phone": "13121266906",\n  "sex": "female",\n  "ID": 14\n },\n {\n  "name": "n",\n  "date": "2020-10-03",\n  "mail": "trent_runte@hotmail.com",\n  "phone": "17122462652",\n  "sex": "female",\n  "ID": 15\n },\n {\n  "name": "h",\n  "date": "2021-04-02",\n  "mail": "jean10@gmail.com",\n  "phone": "17109314490",\n  "sex": "female",\n  "ID": 16\n },\n {\n  "name": "e",\n  "date": "2019-08-24",\n  "mail": "libbie58@hotmail.com",\n  "phone": "16623924476",\n  "sex": "female",\n  "ID": 17\n },\n {\n  "name": "w",\n  "date": "2020-07-23",\n  "mail": "alycia_ferry74@sohu.com",\n  "phone": "13997971072",\n  "sex": "male",\n  "ID": 18\n }\n]',
          columns: [
            {
              title: "ID",
              isCustom: false,
              dataIndex: "ID",
              hide: false,
              sortable: false,
              width: 91.3359375,
              render: { compType: "text", comp: { text: "{{currentCell}}" } },
              align: "left",
            },
            {
              title: "date",
              isCustom: false,
              dataIndex: "date",
              hide: false,
              sortable: true,
              width: 146.640625,
              render: { compType: "text", comp: { text: "{{currentCell}}" } },
              align: "left",
            },
            {
              title: "name",
              isCustom: false,
              dataIndex: "name",
              hide: false,
              sortable: false,
              width: 42,
              render: { compType: "text", comp: { text: "{{currentCell}}" } },
              align: "left",
            },
            {
              title: "mail",
              isCustom: false,
              dataIndex: "mail",
              hide: false,
              sortable: false,
              width: 20,
              render: { compType: "text", comp: { text: "{{currentCell}}" } },
              align: "left",
            },
            {
              title: "phone",
              isCustom: false,
              dataIndex: "phone",
              hide: false,
              sortable: false,
              width: -1,
              render: { compType: "text", comp: { text: "{{currentRow.ID}}" } },
              align: "left",
            },
            {
              title: "sex",
              isCustom: false,
              dataIndex: "sex",
              hide: false,
              sortable: false,
              width: -1,
              render: {
                compType: "text",
                comp: { text: "{{currentOriginalIndex}}" },
              },
              align: "left",
            },
            {
              title: "custom column",
              isCustom: true,
              dataIndex: "69924dc2",
              hide: false,
              sortable: false,
              width: -1,
              render: { compType: "text", comp: { text: "{{currentRow.ID}}" } },
              align: "left",
            },
          ],
          size: "large",
          selection: {
            mode: "single",
            selectedRowKey: "0",
            selectedRowKeys: [],
          },
          pagination: {
            showQuickJumper: false,
            showSizeChanger: false,
            changeablePageSize: { value: 0, defaultValue: "" },
            pageSize: "10",
            total: "",
            pageNo: 1,
            pageSizeOptions: "[10, 20, 50, 100]",
          },
          hidden: "",
        },
        name: "table1",
      },
    },
  },
  queries: [
    {
      compType: "mysql",
      comp: { sql: "", timeout: "10000" },
      id: "2qu36dzm29jd2vm2ihmr6crv",
      name: "query2",
      code: 1,
      message: "",
      data: {},
      extra: {},
      isFetching: false,
      datasourceId: "623878d5320b9d7726fdac5d",
      triggerType: "automatic",
      successTrigger: { compType: "empty", comp: {} },
    },
  ],
};
